/*
 * This source file was generated by the Gradle 'init' task
 */
package com.marshallArts.keeey;

import org.junit.Test;
import static org.junit.Assert.*;

public class LambdaMainTest {
    @Test public void appHasAGreeting() {
        LambdaMain classUnderTest = new LambdaMain();
    }
}
